# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logisticcf <- function(X, Z, K, lambda, max_iter, tol, cap) {
    .Call(`_NDBEC_logisticcf`, X, Z, K, lambda, max_iter, tol, cap)
}

